@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.elementsofpower.spells.shapes;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;