@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.elementsofpower.spelldust;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;