@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.elementsofpower.server;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;