@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.elementsofpower.database.recipes.crafting;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;