@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.elementsofpower.client.renderers.spells;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;