@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.elementsofpower.essentializer;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;