@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.elementsofpower.client;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;