@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.elementsofpower.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;