@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package dev.gigaherz.elementsofpower.integration;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;