@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package gigaherz.elementsofpower.spells;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;